# Generated by Django 4.0.3 on 2022-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=512, unique=True)),
                ('contract_address', models.CharField(max_length=128)),
                ('token_id', models.CharField(default='0', max_length=64)),
                ('chain_id', models.CharField(default='0', max_length=64)),
                ('encrypt_key', models.CharField(max_length=512)),
                ('bind_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'key_list',
            },
        ),
    ]
