# Generated by Django 4.0.3 on 2022-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keylist',
            name='nft_contract_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='keylist',
            name='rpc_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='keylist',
            name='contract_address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
